version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    image: aes_image
    stdin_open: true
    tty: true
    container_name: aes_container
    volumes:
      - type: volume
        source: aes_volume
        target: /home/developer/app

volumes:
  aes_volume: