version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    image: node_template_image
    stdin_open: true
    tty: true
    container_name: node_template_container
    volumes:
      - type: volume
        source: node_template_volume
        target: /home/developer/app

volumes:
  node_template_volume: